name: PR

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title Prefix
        id: title-check
        uses: actions/github-script@v7
        with:
          script: |
            let re = /^(feat|fix|refactor|test|chore)(\([a-z_]+\))?: /g;
            const title = context.payload.pull_request.title;
            if (title.match(re) == null) { process.exit(-1); }
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        if: failure()
        with:
          message: |
            :x: PR title should fullfil regex /^(feat|fix|refactor|test|chore)(\([a-z_]+\))?: /
          comment_tag: pr-title-check
