name: test

on:
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  spectest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup ubuntu
        run: |
          sudo apt-get update && sudo apt-get install qemu-user gcc-aarch64-linux-gnu g++-aarch64-linux-gnu cmake make clang-tidy

      - name: setup submodule
        run: |
          git submodule update --init --depth=1

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 23.x
          cache: "npm"
      - run: npm ci

      - name: demo test chapters
        run: |
          npm run build:demo
          npm run test:c2

      - name: gtest spec
        run: |
          npm run build:spectest
          qemu-aarch64 -L /usr/aarch64-linux-gnu ./build/bin/Spectest
