name: test

on:
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  spectest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup ubuntu
        run: |
          sudo apt-get update && sudo apt-get install qemu-user gcc-aarch64-linux-gnu g++-aarch64-linux-gnu cmake make clang-tidy wabt nlohmann-json3-dev

      - name: setup submodule
        run: |
          git submodule update --init --depth=1

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 23.x
          cache: "npm"
      - run: npm ci

      - name: cross compile arm gtest
        run: |
          cd third_party/googletest && mkdir -p build && cd build && cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/aarch64-linux-gnu-g++ -DCMAKE_C_COMPILER=/usr/bin/aarch64-linux-gnu-gcc && make -j && sudo make install

      - name: gtest spec
        run: |
          mkdir -p tests/testcases/tmp/ 
          for wast_file in tests/testcases/*.wast; do
            json_file="tests/testcases/tmp/$(basename "$wast_file" .wast).json"
            wast2json "$wast_file" --output="$json_file"
          done

          npm run build
          qemu-aarch64 -L /usr/aarch64-linux-gnu ./build/bin/Spectest
