name: test

on:
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup ubuntu
        run: |
          sudo apt-get update && sudo apt-get install qemu-user gcc-aarch64-linux-gnu g++-aarch64-linux-gnu cmake make clang-tidy

      - name: setup submodule
        run: |
          git submodule update --init --depth=1

      - name: build arm gtest
        run: |
          cd third_party/googletest && mkdir build && cd build && cmake .. -DMAKE_INSTALL_PREFIX=./_install -DCMAKE_CXX_COMPILER=/usr/bin/aarch64-linux-gnu-g++ -DCMAKE_C_COMPILER=/usr/bin/aarch64-linux-gnu-gcc && sudo make && sudo make install

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 23.x
          cache: "npm"
      - run: npm ci

      - name: build demo compiler
        run: npm run build:demo

      - name: test chapters
        run: |
          npm run test:c2
