name: test

on:
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # setup environment
      - name: setup ubuntu
        run: |
          sudo apt-get update && sudo apt-get install qemu-user gcc-aarch64-linux-gnu g++-aarch64-linux-gnu cmake make

      - name: setup submodule
        run: |
          git submodule update --init --depth=1 third_party/Tiny-Wasm-Compiler-Learn

      - name: setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - run: npm ci
      - name: setup java
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"

      - name: test chapter1 parser
        run: |
          mkdir build && cd build && cmake .. && make -j && qemu-aarch64 -d unimp,guest_errors -L /usr/aarch64-linux-gnu ./demo/Compiler ../chapters/Chapter01/add.wasm
